---
- name: Download kafka package
  unarchive:
    src: "{{ kafka_install_package }}"
    dest: "{{ kafka_home_dir }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    remote_src: true
