---
- name: Add and enable Kafka service.
  service:
    name: kafka
    state: "{{ kafka_service_state }}"
    enabled: "{{ kafka_service_enabled }}"

- name: Add and enable Kafka service.
  service:
    name: zookeeper
    state: "{{ kafka_zookeeper_service_state }}"
    enabled: "{{ kafka_zookeeper_service_enabled }}"
