---
- name: Reload systemd daemon
  systemd:
    daemon-reload: true

- name: Restart kafka
  systemd:
    state: restarted
    name: kafka

- name: Restart zookeeper
  systemd:
    state: restarted
    name: zookeeper
